spring:

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # or update, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml